# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j3-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter j3lte j3ltekx,$(TARGET_DEVICE)),)

endif
